name: Build and release Android app APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.1.0

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: set env vars for release tag name
      run: |
        echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
        echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

    - uses: ncipollo/release-action@v1.14.0
      with:
        name: "${{ env.NOW }} (commit: ${{ env.sha_short }})"
        tag: "${{ env.sha_short }}"
        commit: main
        artifacts: "app/build/outputs/apk/release/*.apk"
        generateReleaseNotes: true
        makeLatest: true
        artifactErrorsFailBuild: true
